jobs:
  - job: Ursabot
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.6
          architecture: 'x64'
      - script: |
          pip install -r requirements.txt
      - script: |
          flake8 ursabot
          pytest -v --run-integration ursabot

  - job: Arrow
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        'AMD64 Ubuntu 18.04 C++':
          BUILDER: 'AMD64 Ubuntu 18.04 C++'
        'AMD64 Ubuntu 18.04 Python 3':
          BUILDER: 'AMD64 Ubuntu 18.04 Python 3'
        'AMD64 Conda C++':
          BUILDER: 'AMD64 Conda C++'
        'AMD64 Conda R':
          BUILDER: 'AMD64 Conda R'
        AMD64_Conda_Python_27:
          BUILDER: 'AMD64 Conda Python 2.7'
        AMD64_Conda_Python_36:
          BUILDER: 'AMD64 Conda Python 3.6'
        AMD64_Conda_Python_37:
          BUILDER: 'AMD64 Conda Python 3.7'
        AMD64_Java_OpenJDK_8:
          BUILDER: 'AMD64 Java OpenJDK 8'
        AMD64_Java_OpenJDK_11:
          BUILDER: 'AMD64 Java OpenJDK 11'
        AMD64_Debian_9_Rust_1_35:
          BUILDER: 'AMD64 Debian 9 Rust 1.35'
        AMD64_Debian_9_Go_1_12_6:
          BUILDER: 'AMD64 Debian 9 Go 1.12.6'
        AMD64_Debian_9_Go_1_11_11:
          BUILDER: 'AMD64 Debian 9 Go 1.11.11'
        AMD64_Debian_9_NodeJS_11:
          BUILDER: 'AMD64 Debian 9 NodeJS 11'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.6
          architecture: 'x64'
      - script: |
          pip install -e .
      - script: |
          pushd projects/arrow
          ursabot -v project build "$BUILDER"
          popd
