pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.6
      architecture: 'x64'

  - script: |
      pip install -r requirements.txt
      docker ps

  - script: |
      flake8 ursabot
      pytest -v --run-integration ursabot
