
jobs:
  - job: TestUrsabot
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.6
          architecture: 'x64'
      - script: |
          pip install -r requirements.txt
      - script: |
          flake8 ursabot
          pytest -v --run-integration ursabot

  - job: TestArrowBuilder
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        AMD64_Ubuntu_1804_CPP:
          BUILDER: 'AMD64 Ubuntu 18.04 C++'
        AMD64_Ubuntu_1804_Python_3:
          BUILDER: 'AMD64 Ubuntu 18.04 Python3'
          # - 'AMD64 Conda C++'
          # - 'AMD64 Conda R'
          # - 'AMD64 Conda Python 2.7'
          # - 'AMD64 Conda Python 3.6'
          # - 'AMD64 Conda Python 3.7'
          # - 'AMD64 Java OpenJDK 8'
          # - 'AMD64 Java OpenJDK 11'
          # - 'AMD64 Debian 9 Rust 1.35'
          # - 'AMD64 Debian 9 Go 1.12.6'
          # - 'AMD64 Debian 9 Go 1.11.11'
          # - 'AMD64 Debian 9 NodeJS 11'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.6
          architecture: 'x64'
      - script: |
          pip install -e .
      - script: |
          pushd projects/arrow
          ursabot project build $(BUILDER)
          popd
